apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-cpu
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
